Update patch set 1
Patch Set 1: Code-Review-1

not enough
Now I have laterly:
!ENTRY org.eclipse.oomph.p2.core 4 0 2014-06-30 22:49:00.761
!MESSAGE java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/eclipse/eclipsehandledByOomph/oomph/git/org.eclipse.oomph/sites/org.eclipse.oomph.site/target/repository/
!STACK 0
org.eclipse.oomph.p2.P2Exception: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/eclipse/eclipsehandledByOomph/oomph/git/org.eclipse.oomph/sites/org.eclipse.oomph.site/target/repository/
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.collectRepositories(ProfileTransactionImpl.java:777)
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.resolve(ProfileTransactionImpl.java:560)
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.commit(ProfileTransactionImpl.java:324)
	at org.eclipse.oomph.setup.p2.impl.P2TaskImpl.perform(P2TaskImpl.java:677)
	at org.eclipse.oomph.internal.setup.core.SetupTaskPerformer.doPerformNeededSetupTasks(SetupTaskPerformer.java:2288)
	at org.eclipse.oomph.internal.setup.core.SetupTaskPerformer.performNeededSetupTasks(SetupTaskPerformer.java:2246)
	at org.eclipse.oomph.internal.setup.core.SetupTaskPerformer.performTriggeredSetupTasks(SetupTaskPerformer.java:2236)
	at org.eclipse.oomph.internal.setup.core.SetupTaskPerformer.perform(SetupTaskPerformer.java:2178)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$7.run(ProgressPage.java:358)
	at org.eclipse.oomph.setup.ui.wizards.ProgressPage$9$1.run(ProgressPage.java:435)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.net.URISyntaxException: Illegal character in path at index 16: file:/C:/Program Files/eclipse/eclipsehandledByOomph/oomph/git/org.eclipse.oomph/sites/org.eclipse.oomph.site/target/repository/
	at java.net.URI$Parser.fail(Unknown Source)
	at java.net.URI$Parser.checkChars(Unknown Source)
	at java.net.URI$Parser.parseHierarchical(Unknown Source)
	at java.net.URI$Parser.parse(Unknown Source)
	at java.net.URI.<init>(Unknown Source)
	at org.eclipse.oomph.p2.internal.core.ProfileTransactionImpl.collectRepositories(ProfileTransactionImpl.java:748)
	... 10 more

Patch-set: 1
Reviewer: Gerrit User 513 <513@97ee7c02-f12f-4043-b43e-dea463d88b31>
Label: Code-Review=-1